name: Bug Report (T1)
description: Report a problem/bug with the T1-Theme.
labels: [bug]
assignees:
  - Eight-P
  
body:

  # Header
  - type: markdown
    attributes:
      value: |
        ## Please try and isolate the root cause of the issue first!
        e.g. check your CustomCSS and disable any other Theme or Plugin.
        
        If the issue is not caused by T1 alone, but in combination with another addon make sure to include that in the report!
        
        <br/>
        
        ## Please describe the issue in detail and how to reproduce it.
  
  # Main report textarea
  - type: textarea
    attributes:
      label: "T1 Issue report:"
      description: "__(Screenshots can often help)__"
    validations:
      required: true
  
  # Info section sub header
  - type: markdown
    attributes:
      value: |
        <br/>
        
        ## Please include as much information as possible.
        They're not required, but might be very helpful.
        
        <br/>
  
  # Discord client check
  - type: dropdown
    attributes:
      label: "Discord client:"
      description: "__Stable is highly recommended.__"
      multiple: true
      options:
        - Stable (Default)
        - PTB
        - Canary
  
  # Spacer line
  - type: markdown
    attributes:
      value: "##"
  
  # Mod check
  - type: dropdown
    attributes:
      label: "Discord Mod:"
      multiple: true
      options:
        - BetterDiscord
        - Vencord
        - Replugged
        - Other (list below)
  
  # Spacer line
  - type: markdown
    attributes:
      value: "##"
  
  # Platform check
  - type: dropdown
    attributes:
      label: "Platform:"
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - Web (Browser)
  
  # Spacer line
  - type: markdown
    attributes:
      value: "##"
  
  # T1 Version check
  - type: input
    attributes:
      label: "T1 version:"
      description: |
        __There are two versions:__
        __Main:__ At the bottom of the Settings-menu sidebar (might break and only shows when the theme is enabled) | __File version:__ Themes-tab card
  
  # Spacer line
  - type: markdown
    attributes:
      value: "##"
  
  # Additional notes
  - type: textarea
    attributes:
      label: "Additional notes:"
      description: '__If you selected "other" above, you can list them here.__'
  
  # Footnote
  - type: markdown
    attributes:
      value: |
        <br/>
        
        #### Thank you for taking the time to fill out this bug report.
