# CSS build action v2.3
# Build CSS and deploy to dist branch
name: buildCss

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "Themes/**/src/*.scss"

permissions:
  contents: write

jobs:

  DetermineBuilds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      t1: ${{ case (github.event_name == 'workflow_dispatch', 'true', steps.filter.outputs.t1) }}
      snippets: ${{ case (github.event_name == 'workflow_dispatch', 'true', steps.filter.outputs.snippets) }}

    steps:
    - uses: actions/checkout@v6
      if: github.event_name != 'workflow_dispatch'

    - name: Identify file changes.
      if: github.event_name != 'workflow_dispatch'
      uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          t1: 'Themes/T1/src/*.scss'
          snippets: 'Themes/Snippets/src/*.scss'

  Build:
    needs: DetermineBuilds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: 24.x

    - run: npm ci

    # Just gonna do all cp recursively.
    - name: Build T1 css
      if: needs.DetermineBuilds.outputs.t1 == 'true'
      run: |
        npm run buildCSS -w Themes/T1
        cp -r Themes/T1/dist temp-t1

    - name: Build Snippets css
      if: needs.DetermineBuilds.outputs.snippets == 'true'
      run: |
        npm run buildCSS -w Themes/Snippets
        cp -r Themes/Snippets/dist temp-snippets

    - name: Switch to dist branch
      run: |
        git fetch origin dist
        git switch -f dist

    # Needs to remove previous files, I think.
    - name: Add T1 output to dist
      if: needs.DetermineBuilds.outputs.t1 == 'true'
      run: |
        rm -rf Themes/T1/dist
        cp -r temp-t1 Themes/T1/dist

    - name: Add Snippets output to dist
      if: needs.DetermineBuilds.outputs.snippets == 'true'
      run: |
        rm -rf Themes/Snippets/dist
        cp -r temp-snippets Themes/Snippets/dist

    - name: Get status & stage output
      run: |
        git status
        git add **/dist/*.css

    # If nothing was added, this is expected to fail.
    - name: Commit & push changes
      env:
        msg: ${{ case (github.event_name == 'workflow_dispatch', 'workflow dispatch', github.event.head_commit.id) }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "build for: ${{ env.msg }}"
        git push origin dist
