# v1.5
# Build and commit css for T1
name: build-T1
on:
  push:
    branches:
    - master
    paths:
    - "**/T1/src/T1_refresh.main.scss" # _refresh temp. 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: npm ci
    - run: npm run buildCSS -w Themes/T1

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79
      with:
        commit_message: "build for: ${{ github.event.head_commit.id }}"
