# v1.7
# Build and commit css for T1
name: build-T1
on:
  push:
    branches:
    - master
    paths:
    - "**/T1/src/T1.main.scss"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.x

    - run: npm ci
    - run: npm run buildCSS -w Themes/T1

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
      with:
        commit_message: "build for: ${{ github.event.head_commit.id }}"
