# v1.2
# Build and deploy gh-pages
# auto runs after css builds

name: gh-pages
on:
  workflow_run:
    workflows: ["build-Old", "build-T1"]
    types:
      - completed
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4